title: Escaping Vorkuta
description: "Reznov's walkthroughs on CTFs and the such."
author:
  name: "rezn0v"
  email: "reznovisvibing@gmail.com"
  url: "https://rezn0v.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

plugins: [jekyll-paginate]

# Custom variables
owner : "rezn0v"
year : "2020"
